update QLearning
QLearning is looking better. Just need to fix error in env when closing.

AttributeError: 'SchedulerEnvironment' object has no attribute 'window'